version: '3.2'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: punto_de_venta
      MYSQL_USER: user                  # Usuario de la base de datos
      MYSQL_PASSWORD: userpassword      # Contraseña del usuario de la base de datos
    ports:
      - "3306:3306"  # Mapea el puerto 3306 del contenedor al host
    volumes:
      - db_data:/var/lib/mysql  # Persistencia de datos

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_ui
    restart: always
    environment:
      PMA_HOST: db                      # Nombre del servicio MySQL (coincide con "db")
      PMA_PORT: 3306
      PMA_USER: user                    # Usuario configurado en MySQL
      PMA_PASSWORD: userpassword        # Contraseña configurada en MySQL
    ports:
      - "8080:80"  # Mapea el puerto 80 del contenedor al puerto 8080 del host
    depends_on:
      - db

volumes:
  db_data:
